### ISSUE TITLE
List contacts

### ISSUE THREAD

**Issue by derari** [hpi-swt2/Ruby-on-Rails-TDD-example#1]
**As a** contact list user
**I want to** see name and age of my contacts
**so that** I can quickly find entries in the list. 
##### Acceptance Criteria
- [ ] `contact/index` lists all contacts
- [ ] First name, last name, and age shown for each
##### Tasks
- [ ] Add `age` method to `Contact`
- [ ] Fetch all contacts in contact controller
- [ ] Render list in `app/views/contact/index.html.erb`

**Comment by derari** [comment]
(reopened for educational purposes)
